{% set name = "crispy-bootstrap4" %}
{% set version = "2024.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/crispy-bootstrap4-{{ version }}.tar.gz
  sha256: 503e8922b0f3b5262a6fdf303a3a94eb2a07514812f1ca130b88f7c02dd25e2b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - django-crispy-forms >=1.14.0
    - django >=3.2

test:
  imports:
    - crispy_bootstrap4
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/django-crispy-forms/crispy-bootstrap4
  summary: Bootstrap4 template pack for django-crispy-forms
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
