# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: crispy-bootstrap4
  version: "2026.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 66f8f14bf9c2c16ed94243236ed253a94e5a625afa1ee64022ce29db98c6cd85

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }},<4.0
    - django-crispy-forms >=2.3
    - django >=4.2
    # - pytest-django
    # - pytest

tests:
  - python:
      imports:
        - crispy_bootstrap4
      python_version: ${{ python_min }}.*
      pip_check: true

about:
  summary: Bootstrap4 template pack for django-crispy-forms
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/django-crispy-forms/crispy-bootstrap4

extra:
  recipe-maintainers:
    - rxm7706
